### PR TITLE
Tpo 00

### PR DESCRIPTION
**Pull request by TomODwyer-SES**
This is a pull request to add my recent modifications to the latest version.

Modification were made on topic branch TPO_00

Modified makefile and removed ses41_gf.exe from repo

Changed SESVER to "4.2"

Added simple on screen output.

### CODE REVIEW

**Review by iamchermac — APPROVED** [review]
Hi @TomODwyer-SES 

I had a review and all code changes look fine (i.e. no visible errors).

There are still two hangovers in INPUT.FOR from the Front Page Update. Namely, OpenSES version hardcoded (line 65) and the version variable (line 102). Neither of these are critical, however adding 'OpenSES' to the FORMAT on line 102 could prove useful in the future.

A 'good-to-have' would have been to have a carriage return to the beginning of the line feed for the Simulation Time output to console as opposed to the continuous output to console (noting that piping to a file for simulation logging would still have all this output). This could prove useful when batch executing, especially that we won't be including a switch to turn off output at present. I spent a couple of hours trying to achieve this in my local repo (using a combination of $, + and flushing) but no success.

Notwithstanding the above, I would recommend we accept all changes as is to meet the action items.

**Comment by TomODwyer-SES** [comment]
I've update input.for with some of the things mentioned above.
please look over.
-Tom

**Review by iamchermac — APPROVED** [review]
I am happy with the changes to .gitignore and INPUT.FOR.

The simulation execution timestamp in the .OUT is a great addition.

**Comment by NeverGray** [comment]
Thanks for the efforts! On Friday, I'll review the detail. If everything looks good, I'll create an OpenSES executable. I'll then prepare a report that compares the outputs of SES 4.1 and OpenSES 4.2.

**Pull request merged**
