### PR TITLE
Input file versions

### PR DESCRIPTION
**Pull request by ECB2020**
As per discussions on thread #21 the code and its verification files are ready for review

### CODE REVIEW

**Comment by iamchermac** [comment]
Hi @ECB2020,

Thank you for submitting your pull request and the contributions you have made to OpenSES so far. We have undertaken an initial review of your submitted changes and agree with many of the suggested changes, however we do have some initial comments. 

### **Overarching**

The most overarching comment would be the code base by which your changes have been added. We have noticed your code base is the main branch of OpenSES 4.2. A 'developer' branch can be fetched from the GitHub repo. The intent is that this developer branch would be used for the community to implement changes, between 'blessed' releases of OpenSES (e.g. 4.3, 4.4, 5.0), which they would like to add back to the project.

On reflection of [my reply to your discussion thread](https://github.com/Open-SES/OpenSES/discussions/21#discussioncomment-3959626) on adding versions to the input file, I did not convey the process explicitly and clearly enough. Therefore, we will be adding a good housekeeping guide for making pull requests and place it in a prominent place on the wiki. We will be taking cues from some of the actions you have made during your pull request to help with this guide (e.g. your excellent documenting of changes). This alone has been a valuable contribution by yourself.

The above suggests that it would ultimately be more efficient for us to reject this request in order to allow the merge of your changes into the developer branch to take place on your end. However, with a mind to reducing the number of iterations around this submission, we will also provide all additional comments at the same time so that your next pull request will have current changes of the developer branch, changes addressing these comments, and potentially other additions you may have progressed with.

If you find it helpful, I can arrange a meeting to show how you may apply your updates to the ‘developer' branch in an efficient way. 

### **Initial Comments** 

We agree in principle on the changes suggested to the approach of Fortran version. "Implicit none", coding in Fortran 95, and the edits to the makefile are welcomed. However, to allow consistency within the code, we think it would be best to keep submitted code as ALL CAPS. Depending on which IDE a developer uses, this may be easily done in preparation for submitting the code, to make day-to-day coding less cumbersome. We may also look to add some 'QA' scripts that can help make pre-pull request preparations.

The updated OpenSES copyright years in INPUT is appreciated, but we would not want to edit the specific date of the code in this location. The date should automatically be updated within the executable during the make process. **A prerequisite of providing a compiled and 'working' executable with pull requests will be the preferred way forward**.

In relation to the error associated with not providing an OpenSES version number on Form 1B, we feel it would be better to use a warning system as opposed to a terminating error. This would allow best backward compatibility with SES 4.1 and potential adoption of OpenSES by users of SES 4.1. Noting that _OpenSES is a fork of the original SES 4.1_ program, it should be the assumed behaviour if this version entry is not present (reads the input file as SES 4.1 with IP calculations, and for example, a jet fan derating option would not be initiated unless a proper OpenSES version is present). The warning could be implemented to command line and the output file, for example. In essence the internal code for OpenSES could default this entry to '4.2' as OpenSES 4.2 has the same computational algorithms as SES 4.1. _Note: similar practice occurs with input entries that are not present (e.g. default values of zero)_. 

### **Comments Pending Detailed Review**

We are still in the process of undertaking a deeper review of code changes in hopes of providing a full complement of comments to limit iterations before being able to merge your pull request into the developer branch available on GitHub. We will aim to have that finalised within the next fortnight. We wanted to provide this initial feedback to allow any amendments of the initial comments and this detailed review to happen in parallel. 

Thank you again for your contributions to date. You have helped to further our excitement about the potential of OpenSES, and we also hope it inspires other members of the Tunnel Ventilation community to join in.

Kind Regards, 

Chermac, **on behalf of the Engineers of OpenSES**

**Comment by ECB2020** [comment]
Thanks for the comments.  Responses are as follows:

#### Overarching
OK, so I'm pushing to the wrong branch.  Thank you for offering to have a meeting in which one of you shows me how to apply my updates to a different branch, that would be very useful.  I'll be in touch by email to arrange.

#### All caps
I prefer putting new code in lower case (doing that makes it easy to spot new code in amongst original code).  But it's your repository, and it's easy enough for me to tell the text editor to convert the files to all caps.  Do you want that to apply to the .f95 files, or just the .FOR files?

#### Auto-set the program date
I don't know how to get the current date during the make process (and I'm not willing to spend time figuring it out - I hate working on makefiles!).  I'll revert the relevant parts of the files so that they have the same text as the original code.

#### Upload an executable
OK.  I develop and upload stuff from macOS and only ever test on Windows/linux, but it should be easy enough to copy over the Windows executable (I assume you want a Windows executable).

#### Treat an absent version number as 4.1
I'll change it as follows:
-  If the 31st to 40th characters in form 1B are blank, INPVER is set to 4200.
- If the 31st to 40th characters in form 1B are blank, text will be written to the screen and to the .OUT file suggesting that the user add a version number and that 4.1's rules for calculation will be used.
- Error 1001 (there was no version number in the input file) will be removed.
- If the 31st to 40th characters contain a number below 4.1 it triggers the existing error 1003.

I think that's what you're asking for, holler if it isn't.

Regards,

Ewan

**Comment by NeverGray** [comment]
### Proposal to Abandon ALL CAPS
Ewan makes a good point, and I now support that the **new code should abandon All CAPS**. In addition to making updates to 4.1 easier to spot, lowercase letters are the **current programming convention**; see examples at https://www.fortran90.org/src/best-practices.html.

Another reason to abandon All CAPS is that OpenSES's BSD 3-Clause License only applies to updates to SES 4.1. (One company has a misconception that OpenSES's license includes the original SES 4.1 code). Changing the letter convention helps people distinguish OpenSES code vs. SES 4.1 code.

@iamchermac @TomODwyer-SES 
Would you agree to accept Ewan's proposal **new code should abandon All CAPS** with my support? Should I get Conor, Scott, or Vej to evaluate as well? Should I create a poll?

**Comment by iamchermac** [comment]
> ### Proposal to Abandon ALL CAPS
> Ewan makes a good point, and I now support that the **new code should abandon All CAPS**. In addition to making updates to 4.1 easier to spot, lowercase letters are the **current programming convention**; see examples at https://www.fortran90.org/src/best-practices.html.
> 
> Another reason to abandon All CAPS is that OpenSES's BSD 3-Clause License only applies to updates to SES 4.1. (One company has a misconception that OpenSES's license includes the original SES 4.1 code). Changing the letter convention helps people distinguish OpenSES code vs. SES 4.1 code.
> 
> @iamchermac @TomODwyer-SES 
> I could create a poll. Would you agree to accept Ewan's proposal **new code should abandon All CAPS** with my support? Should I get Conor, Scott, or Vej to evaluate as well? Should I create a poll?

Agreed; there are those benefits (code identification and differentiation from SES 4.1).

A poll is ideal to get a quick yay or nay, and it would be best to get consensus from everyone currently looking to contribute to code development.

**Comment by NeverGray** [comment]
See Poll #23, Proposal: Abandon ALL CAPS in future code Contributions

**Comment by iamchermac** [comment]
> Thanks for the comments. Responses are as follows:
> 
> #### Overarching
> OK, so I'm pushing to the wrong branch. Thank you for offering to have a meeting in which one of you shows me how to apply my updates to a different branch, that would be very useful. I'll be in touch by email to arrange.
> 
> #### All caps
> I prefer putting new code in lower case (doing that makes it easy to spot new code in amongst original code). But it's your repository, and it's easy enough for me to tell the text editor to convert the files to all caps. Do you want that to apply to the .f95 files, or just the .FOR files?
> 
> #### Auto-set the program date
> I don't know how to get the current date during the make process (and I'm not willing to spend time figuring it out - I hate working on makefiles!). I'll revert the relevant parts of the files so that they have the same text as the original code.
> 
> #### Upload an executable
> OK. I develop and upload stuff from macOS and only ever test on Windows/linux, but it should be easy enough to copy over the Windows executable (I assume you want a Windows executable).
> 
> #### Treat an absent version number as 4.1
> I'll change it as follows:
> 
> * If the 31st to 40th characters in form 1B are blank, INPVER is set to 4200.
> * If the 31st to 40th characters in form 1B are blank, text will be written to the screen and to the .OUT file suggesting that the user add a version number and that 4.1's rules for calculation will be used.
> * Error 1001 (there was no version number in the input file) will be removed.
> * If the 31st to 40th characters contain a number below 4.1 it triggers the existing error 1003.
> 
> I think that's what you're asking for, holler if it isn't.
> 
> Regards,
> 
> Ewan

Hi again @ECB2020. Not necessarily which branch you are pushing to, but rather your starting point. That is, if a developer was downloading the repo from the browser wiki, they should toggle over to the developer branch (top left above repo directory structure). Alternatively, if doing a remote pull/fetch, the first step is to check that the developer branch is available and if so switch to that branch before starting to code.

I will be in touch via email this week to arrange a brief meeting; I just need to see what time sensibly works for both our time zones.

The outcome of the [poll on ALL CAPS](https://github.com/Open-SES/OpenSES/discussions/23#discussion-4622943) looks like the majority are happy to move forward with a lowercase convention to help differentiate new code (notwithstanding the fact that code added between SES 4.1 and OpenSES 4.2 will already be in CAPS). That's a QA related to-do for a later date.

With regards to the make file and date, we will look in parallel at automating that (if it indeed is not done that way at present). For day to day development git would handle tracking the 'when' of code, while the reflection of a release date for a version is meant for embedding into executables.

Finally, with regards to executables and reflecting on your point, developers should provide as many (Windows, macOS, Linux) as they have access too. Ideally in the long term the project will hopefully be able to validate the executables work as intended and make those available. I agree with your suggested approach for everything else.

Regards,

Chermac

**Comment by NeverGray** [comment]
There is no difference between the simulation outputs of Pull Request 22 and OpenSES 4.2 for input files inferno and normal. The attached files demonstrate my check. 

[Comparison of Pull Request 22 to OpenSES 4p2.pdf](https://github.com/Open-SES/OpenSES/files/11424777/
[inferno4p2_to_inferno4p2_pr22.xlsx](https://github.com/Open-SES/OpenSES/files/11424781/inferno4p2_to_inferno4p2_pr22.xlsx)
[normal4p2_to_normal4p2_pr22.xlsx](https://github.com/Open-SES/OpenSES/files/11424782/normal4p2_to_normal4p2_pr22.xlsx)
Comparison.of.Pull.Request.22.to.OpenSES.4p2.pdf)

**Pull request merged**
